name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository

    - name: Use .NET Core 3.1.301
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: dotnet restore
      run: dotnet restore /nologo

    - name: dotnet build
      run: dotnet build -c Release --no-restore --nologo     
